# Generated by Django 4.2.2 on 2023-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketinstance',
            options={'ordering': ['due_to']},
        ),
    ]
