# Generated by Django 4.2.2 on 2023-09-05 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egidas', '0003_remove_place_coordinates_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresas'),
        ),
        migrations.AlterField(
            model_name='place',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
