# Generated by Django 4.2.2 on 2023-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0004_place_address_alter_place_favourited_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketinstance',
            options={'ordering': ['due_to'], 'verbose_name': 'BBilieto egzempliorius', 'verbose_name_plural': 'Bilietų egzemplioriai'},
        ),
        migrations.AlterModelOptions(
            name='ticketorder',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Bilieto užsalymas', 'verbose_name_plural': 'Bilietų užsakymai'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='favourited_by',
        ),
        migrations.AddField(
            model_name='place',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Nuotrauka'),
        ),
    ]
