# Generated by Django 4.2.2 on 2023-09-07 07:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0005_alter_ticketinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paslaugos pavadinimas'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Apie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Suaugusiems'), ('V', 'Vaikams'), ('N', 'Neįgaliems ir pencininkams'), ('B', 'Bendrinis'), ('N', 'Anykštenams')], default='B', help_text='Bilieto tipas', max_length=4),
        ),
    ]
