# Generated by Django 4.2.2 on 2023-09-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0006_ticket_service_alter_place_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketinstance',
            name='ticket_order',
        ),
        migrations.AddField(
            model_name='ticketinstance',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_Instances', to='egidas.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Suaugusiems'), ('V', 'Vaikams'), ('N', 'Neįgaliems ir pencininkams'), ('B', 'Bendrinis'), ('N', 'Anykštėnams'), ('M', 'Moksleiviams ir studentams')], default='B', help_text='Bilieto tipas', max_length=4),
        ),
    ]
