# Generated by Django 4.2.2 on 2023-09-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0007_remove_ticketinstance_ticket_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketinstance',
            options={'ordering': ['due_to'], 'verbose_name': 'Bilieto egzempliorius', 'verbose_name_plural': 'Bilietų egzemplioriai'},
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ticketinstance',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_Instances', to='egidas.ticketorder'),
        ),
        migrations.AddField(
            model_name='ticketinstance',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kiekis'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Suaugusiam', 'Suaugusiems'), ('Vaikams', 'Vaikams'), ('Pens/Neįg', 'Neįgaliems ir pencininkams'), ('Bendrinis', 'Bendrinis'), ('Anykštėnui', 'Anykštėnams'), ('Stud/Moksl', 'Moksleiviams ir studentams')], default='Bendrinis', help_text='Bilieto tipas', max_length=50),
        ),
    ]
