# Generated by Django 4.2.2 on 2023-09-07 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0008_alter_ticketinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Suma viso:'),
        ),
    ]
