# Generated by Django 4.2.2 on 2023-09-07 14:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egidas', '0009_remove_ticketorder_ticket_alter_ticketorder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Pirkimo data')),
            ],
            options={
                'verbose_name': 'Bilieto užsalymas',
                'verbose_name_plural': 'Bilietų užsakymai',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Kiekis')),
                ('due_to', models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 6, 17, 26, 18, 866101), null=True, verbose_name='Galojimas iki')),
                ('status', models.CharField(choices=[('G', 'Galiojantis'), ('P', 'Panaudotas'), ('N', 'Nebegalioja'), ('A', 'Atšauktas')], default='G', max_length=1)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_items', to='egidas.order')),
            ],
            options={
                'verbose_name': 'Bilieto egzempliorius',
                'verbose_name_plural': 'Bilietų egzemplioriai',
                'ordering': ['due_to'],
            },
        ),
        migrations.CreateModel(
            name='TicketCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egidas.ticket')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketInstance',
        ),
        migrations.DeleteModel(
            name='TicketOrder',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_items', to='egidas.ticketcopy'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='egidas.orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
