# Generated by Django 4.2.2 on 2023-09-07 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0010_order_orderitem_ticketcopy_remove_ticketorder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Užsalymas', 'verbose_name_plural': 'užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['due_to'], 'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymo eilutės'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ticket_copy',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_items', to='egidas.ticket'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 6, 18, 25, 5, 235998), null=True, verbose_name='Galojimas iki'),
        ),
        migrations.DeleteModel(
            name='TicketCopy',
        ),
    ]
