# Generated by Django 4.2.2 on 2023-09-07 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0011_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 6, 18, 40, 25, 71295), null=True, verbose_name='Galojimas iki'),
        ),
    ]
