# Generated by Django 4.2.2 on 2023-09-08 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0013_order_items_alter_orderitem_due_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 7, 10, 53, 22, 65112), null=True, verbose_name='Galojimas iki'),
        ),
    ]
