# Generated by Django 4.2.2 on 2023-09-09 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0015_alter_orderitem_due_to_alter_ticket_type_profilis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 8, 10, 23, 4, 286961), null=True, verbose_name='Galojimas iki'),
        ),
    ]
