# Generated by Django 4.2.2 on 2023-09-09 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0016_alter_orderitem_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 8, 12, 12, 33, 477665), null=True, verbose_name='Galojimas iki'),
        ),
    ]
