# Generated by Django 4.2.2 on 2023-09-09 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0017_alter_orderitem_due_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('G', 'Gautas'), ('I', 'Ivykdytas'), ('A', 'Atšauktas'), ('L', 'Laukiama apmokėjimo')], default='G', help_text='Užsakymo statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 8, 12, 34, 1, 460844), null=True, verbose_name='Galojimas iki'),
        ),
    ]
