# Generated by Django 4.2.2 on 2023-09-09 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egidas', '0018_order_status_alter_orderitem_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 8, 14, 13, 8, 355940), null=True, verbose_name='Galojimas iki'),
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Atsiliepimas')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='placereview_set', to='egidas.place')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
