# Generated by Django 4.2.2 on 2023-09-09 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0020_alter_placereview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 8, 20, 10, 23, 556619), null=True, verbose_name='Galojimas iki'),
        ),
    ]
