# Generated by Django 4.2.2 on 2023-09-10 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0021_alter_orderitem_due_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='egidas.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 9, 10, 55, 26, 654036), null=True, verbose_name='Galojimas iki'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Nuotrauka'),
        ),
    ]
