# Generated by Django 4.2.5 on 2023-09-11 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0024_remove_orderitem_ticket_copy_orderitem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_to', models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 10, 20, 4, 25, 606473), null=True, verbose_name='Galojimas iki')),
                ('status', models.CharField(choices=[('G', 'Galiojantis'), ('P', 'Panaudotas'), ('N', 'Nebegalioja'), ('A', 'Atšauktas')], default='G', max_length=1)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_copies', to='egidas.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='egidas.ticketcopy'),
        ),
    ]
