# Generated by Django 4.2.5 on 2023-09-11 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0025_ticketcopy_orderitem_ticket_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketcopy',
            name='due_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 10, 20, 10, 1, 159998), null=True, verbose_name='Galojimas iki'),
        ),
    ]
