# Generated by Django 4.2.5 on 2023-09-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egidas', '0026_remove_orderitem_status_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcopy',
            options={'verbose_name': 'Unikalus bilietas', 'verbose_name_plural': 'Unikalūs bilietai'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ticket_copy',
        ),
        migrations.AddField(
            model_name='ticketcopy',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_copies', to='egidas.orderitem'),
        ),
        migrations.AlterField(
            model_name='ticketcopy',
            name='due_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Galojimas iki'),
        ),
    ]
